/** @format */

import React, { useContext, useEffect, useState } from 'react';
import { DataContext } from '../../context/DataContext';
import { MdHelpOutline, MdEventNote } from 'react-icons/md';
import { useParams } from 'react-router-dom';
import useAppsApi from '../../hooks/useAppsApi';
import Footer from '../Footer';
import ActivityPerformance from './ActivityPerformance';
import AdunitPerformance from './AdunitPerformance';
import { Spinner } from 'react-bootstrap';
import { LuExternalLink } from 'react-icons/lu';
import Select from 'react-select';
import { overViewSelectOption } from '../../utils/helper';

const AppDetailsContentBox = () => {
  const { sidebarActive } = useContext(DataContext);
  const { id } = useParams();

  const [appOverviewData, setAppOverviewData] = useState([]);
  const [overviewSelect, setOverviewSelect] = useState(1);

  const formData = new FormData();
  formData.append('user_id', localStorage.getItem('id'));
  formData.append('user_token', localStorage.getItem('token'));
  formData.append('app_auto_id', id);
  const fetchData = async () => {
    try {
      const response = await useAppsApi('app-overview', formData);
      setAppOverviewData(response);
    } catch (error) {
      throw new Error(error);
    }
  };
  useEffect(() => {
    fetchData();
  }, [id]);

  const customStyles = {
    option: (provided) => ({
      ...provided,
      color: 'black',
    }),
  };

  return appOverviewData.length === 0 ? (
    <div className='shimmer-spinner'>
      <Spinner animation='border' variant='secondary' />
    </div>
  ) : (
    <div className={`right-box-wrap ${sidebarActive ? 'open-box' : ''}`}>
      <div className='main-box-wrapper pdglr24 app-overview'>
        <div className='main-box-row'>
          <div className='top-bar'>
            <h1 className='title'>App overview</h1>
          </div>
          <div className='app-info'>
            <div className='app-item'>
              <div className='app-img'>
                <img
                  alt=''
                  aria-hidden='true'
                  className='app-icon'
                  leading=''
                  src={appOverviewData?.app_info?.app_icon}
                />
              </div>
              <div className='label-container'>
                <span className='primary-label'>
                  {appOverviewData?.app_info?.app_display_name}
                  <a
                    href={
                      appOverviewData?.app_info?.app_platform == 2
                        ? `https://play.google.com/store/apps/details?id=${appOverviewData?.app_info?.app_store_id}`
                        : `https://apps.apple.com/app/${appOverviewData?.app_info?.app_store_id}`
                    }
                    target='_blank'
                    className='external-link-icon'
                  >
                    <LuExternalLink />
                  </a>
                </span>
                <span className='secondary-label'>
                  <span>
                    {(appOverviewData?.app_info?.app_platform == '1' &&
                      'IOS') ||
                      (appOverviewData?.app_info?.app_platform == '2' &&
                        'Android')}
                  </span>
                  <span className='divider'>|</span>
                  <span>Admin</span>
                </span>
              </div>
            </div>
          </div>
          <div className='box-row grey-box mrgb16'>
            <div className='sub-title pdglr16 pdgtb16 w-color'>
              Total estimated earnings
              <div className='tooltip-row'>
                <MdHelpOutline className='help_icon' />
                <div className='tooltip-box'>
                  <div className='content-container'>
                    <h4>Total estimated earnings</h4>
                    <p>
                      An overview of your estimated earnings generated by ads
                      served from all ad sources.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className='box-wrap pdglr16'>
              <div className='scorecard'>
                <div className='label-name'>Today so far</div>

                <div className='label-value copy-text'>
                  <span>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_today_so_far
                    }
                  </span>
                  <div className='copyMessage'>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_today_so_far
                    }
                  </div>
                </div>
              </div>
              <div className='scorecard'>
                <div className='label-name'>Yesterday so far</div>
                <div className='label-value copy-text'>
                  <span>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_yesterday_so_far
                    }
                  </span>
                  <div className='copyMessage'>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_yesterday_so_far
                    }
                  </div>
                </div>
              </div>
              <div className='scorecard'>
                <div className='label-name'>This Month so far</div>
                <div className='label-value copy-text'>
                  <span>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_this_month_so_far
                    }
                  </span>
                  <div className='copyMessage'>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_this_month_so_far
                    }
                  </div>
                </div>
              </div>
              <div className='scorecard'>
                <div className='label-name'>Last Month so far</div>
                <div className='label-value copy-text'>
                  <span>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_last_month_so_far
                    }
                  </span>
                  <div className='copyMessage'>
                    {
                      appOverviewData?.app_info_eastimated_earnings
                        ?.app_info_last_month_so_far
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className='dropdown-row mrgt16 mrgb16'>
            <div className='mui-select'>
              <MdEventNote className='note_icon' />
              <Select
                placeholder={
                  <div className='select-placeholder'>Today so far</div>
                }
                value={overViewSelectOption.value}
                options={overViewSelectOption}
                onChange={(e) => setOverviewSelect(e.value)}
                className='overview-select'
                classNamePrefix='custom-overview-select'
                styles={customStyles}
                isSearchable={false}
                theme={(theme) => ({
                  ...theme,
                  borderRadius: 0,
                  border: 0,
                  colors: {
                    ...theme.colors,
                    primary25: '#eee',
                    primary: '#eee',
                  },
                })}
              />
            </div>
          </div>
          <div className='feed-cards'>
            {/* <div className='box-row box2'>
              <div className='sm-title'>
                Estimated revenue by source: US$0.00
              </div>
              <div className='card-content pdglr16'>
                <div className='revenue-chart'>
                  <EstimateRevenueChart />
                </div>
              </div>
            </div> */}

            <ActivityPerformance overviewSelect={overviewSelect} />
            <AdunitPerformance overviewSelect={overviewSelect} />
          </div>
        </div>

        <Footer />
      </div>
    </div>
  );
};

export default AppDetailsContentBox;
