/** @format */

import React, { useContext, useEffect, useState } from 'react';
import { MdHelpOutline, MdEventNote } from 'react-icons/md';
import { DataContext } from '../../context/DataContext';
import { Spinner } from 'react-bootstrap';
import useApi from '../../hooks/useApi';
import Footer from '../Footer';
import AppPerformance from './AppPerformance';
import HomeActivityPerformance from './HomeActivityPerformance';
import Select from 'react-select';
import { overViewSelectOption } from '../../utils/helper';
import TopPerformanceAdUnit from './TopPerformanceAdUnit';
import TopPerformanceCountry from './TopPerformanceCountry';

const RightContentBox = () => {
  const { sidebarActive } = useContext(DataContext);

  const [estimatedEarnings, setEstimatedEarnings] = useState([]);
  const [estimatedEarningsSelect, setEstimatedEarningsSelect] = useState(1);

  const formData = new FormData();
  formData.append('user_id', localStorage.getItem('id'));
  formData.append('user_token', localStorage.getItem('token'));
  const fetchData = async () => {
    try {
      const response = await useApi(
        'get-dashboard-eastimated-earnings',
        formData
      );
      setEstimatedEarnings(response?.data);
    } catch (error) {
      throw new Error(error);
    }
  };
  useEffect(() => {
    fetchData();
  }, []);
  const customStyles = {
    option: (provided) => ({
      ...provided,
      color: 'black',
    }),
  };

  return (
    <div className={`right-box-wrap ${sidebarActive ? 'open-box' : ''}`}>
      {estimatedEarnings.length === 0 ? (
        <div className='shimmer-spinner'>
          <Spinner animation='border' variant='secondary' />
        </div>
      ) : (
        <div className='main-box-wrapper pdglr24'>
          <div>
            <div className='top-bar'>
              <h1 className='title'>Home</h1>
            </div>
            <div className='main-box-row'>
              <div className='box-row grey-box mrgb16'>
                <div className='sub-title pdglr16 pdgtb16 w-color'>
                  Total estimated earnings
                  <div className='tooltip-row'>
                    <MdHelpOutline className='help_icon' />
                    <div className='tooltip-box'>
                      <div className='content-container'>
                        <h4>Total estimated earnings</h4>
                        <p>
                          An overview of your estimated earnings generated by
                          ads served from all ad sources.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='box-wrap pdglr16'>
                  <div className='scorecard'>
                    <div className='label-name'>Today so far</div>
                    <div className='label-value copy-text'>
                      {estimatedEarnings?.dashboard_today_so_far}
                      <div className='copyMessage'>
                        {estimatedEarnings?.dashboard_today_so_far}
                      </div>
                    </div>
                  </div>
                  <div className='scorecard'>
                    <div className='label-name'>Yesterday so far</div>
                    <div className='label-value copy-text'>
                      {estimatedEarnings?.dashboard_yesterday_so_far}
                      <div className='copyMessage'>
                        {estimatedEarnings?.dashboard_yesterday_so_far}
                      </div>
                    </div>
                  </div>
                  <div className='scorecard'>
                    <div className='label-name'>This Month so far</div>
                    <div className='label-value copy-text'>
                      {estimatedEarnings?.dashboard_this_month_so_far}
                      <div className='copyMessage'>
                        {estimatedEarnings?.dashboard_this_month_so_far}
                      </div>
                    </div>
                  </div>
                  <div className='scorecard'>
                    <div className='label-name'>Last Month so far</div>
                    <div className='label-value copy-text'>
                      {estimatedEarnings?.dashboard_last_month_so_far}
                      <div className='copyMessage'>
                        {estimatedEarnings?.dashboard_last_month_so_far}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className='dropdown-row mrgt16 mrgb16'>
                <div className='mui-select'>
                  <MdEventNote className='note_icon' />
                  <Select
                    placeholder={
                      <div className='select-placeholder'>Today so far</div>
                    }
                    value={overViewSelectOption.value}
                    options={overViewSelectOption}
                    onChange={(e) => setEstimatedEarningsSelect(e.value)}
                    className='overview-select'
                    classNamePrefix='custom-overview-select'
                    styles={customStyles}
                    isSearchable={false}
                    theme={(theme) => ({
                      ...theme,
                      borderRadius: 0,
                      border: 0,
                      colors: {
                        ...theme.colors,
                        primary25: '#eee',
                        primary: '#eee',
                      },
                    })}
                  />
                </div>
              </div>
              <div className='feed-cards'>
                <HomeActivityPerformance
                  overviewSelect={estimatedEarningsSelect}
                />
                {/* <TopPerformanceAdUnit overviewSelect={estimatedEarningsSelect} /> */}
                <AppPerformance overviewSelect={estimatedEarningsSelect} />
                {/* <TopPerformanceCountry overviewSelect={estimatedEarningsSelect} /> */}
              </div>
            </div>
          </div>

          <Footer />
        </div>
      )}
    </div>
  );
};

export default RightContentBox;
